### ISSUE TITLE
Danbooru client.favorite_remove(post_id) bug

### ISSUE THREAD

**Issue by Razator73** [LuqueDaniel/pybooru#51]
I am having an issue with the favorite_remove() function. It will remove the favorite as expected, but it throws an error while doing it. When I refresh my favorites the post is no longer there, but it'd be nice to not see the error.

```python
from pybooru import Danbooru

client = Danbooru('danbooru', username=$USERNAME, api_key=$API_KEY')
post_id = $POST  # as an int
client.favorite_remove(post_id)
```
I get the following error:

```
Traceback (most recent call last):
  File "/home/ryan/.local/share/virtualenvs/img-scraper-CPlRbv_X/lib/python3.8/site-packages/pybooru/pybooru.py", line 179, in _request
    return response.json()
  File "/home/ryan/.local/share/virtualenvs/img-scraper-CPlRbv_X/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ryan/.pyenv/versions/3.8.0/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/ryan/.pyenv/versions/3.8.0/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ryan/.pyenv/versions/3.8.0/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ryan/.local/share/virtualenvs/img-scraper-CPlRbv_X/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-102-8ebb0139f2f3>", line 1, in <module>
    client.favorite_remove(3694909)
  File "/home/ryan/.local/share/virtualenvs/img-scraper-CPlRbv_X/lib/python3.8/site-packages/pybooru/api_danbooru.py", line 437, in favorite_remove
    return self._get('favorites/{0}.json'.format(post_id), method='DELETE',
  File "/home/ryan/.local/share/virtualenvs/img-scraper-CPlRbv_X/lib/python3.8/site-packages/pybooru/danbooru.py", line 86, in _get
    return self._request(url, api_call, request_args, method)
  File "/home/ryan/.local/share/virtualenvs/img-scraper-CPlRbv_X/lib/python3.8/site-packages/pybooru/pybooru.py", line 185, in _request
    raise PybooruError("JSON Error: {0} in line {1} column {2}".format(
pybooru.exceptions.PybooruError: JSON Error: Expecting value in line 1 column 1
```
## My Environment
* Pybooru Version: 4.2.0
* Python Version: 3.8.0
* Danbooru / Moebooru site: Danbooru
* Operating System and version: Ubuntu 18.04 LTS

**Comment by LuqueDaniel** [comment]
Thanks for the report!
